### ISSUE TITLE
Certain DCTLs not working

### ISSUE THREAD

**Issue by robynsun-love** [MoazElgabry/DCTLs#2]
Hi, again!

I'd also like to report that the Filmic Contrast and Ratio Shaper DCTLs aren't working for me. Not sure why. 

For reference, I'm using thatcherfreeman's DCTL Interpreter Fuse in order to load DCTLs within Fusion Lite 18.1.3, and I am using an M1 Macbook running MacOS Monterey 12.0.1.

**Comment by MoazElgabry** [comment]
Thanks for pointing that out.
I could replicate the problem on my end and it was a simple fix, see if that fixes it for you.
